### PR TITLE
add IDN resolver

### LINKED ISSUE #938: netx/resolver: IDN not supported when using miekg/dns
As we learned in https://github.com/ooni/probe-engine/pull/936 and https://github.com/ooni/probe-engine/commit/5a373e6b5a8067e28096dada0966d09e7718d0c2, `netx/resolver` does not support IDN when we are using the `miekg/dns` based resolvers as opposed to Golang's resolver. We should try and improve upon that.

### PR DESCRIPTION
**Pull request by xhdix**
Fix #938

### CODE REVIEW

**Comment by bassosimone** [comment]
@xhdix would updating and merging master into this PR? I've just committed a change so that we run more comprehensive checks opened by contributors, and I'd like to see these checks running before proceeding with review. Thanks!

**Comment by xhdix** [comment]
It's done. Need fixup?

**Comment by bassosimone** [comment]
> It's done.

Thanks!

> Need fixup?

No, it's fine, I am going to squash and merge anyway

**Comment by bassosimone** [comment]
@xhdix I was looking now at the coverage, which is decreasing. It seems we are missing a check where the conversion for IDNA domain names fails. Please, see the lines that are not covered:

https://coveralls.io/jobs/67999399/source_files/2428426956.

Based on the implementation, it seems to me we should be able to provoke an error by controlling the overall length of the domain name (see https://github.com/golang/net/blob/62affa334b73/idna/idna10.0.0.go#L387).

**Comment by xhdix** [comment]
> Based on the implementation, it seems to me we should be able to provoke an error by controlling the overall length of the domain name (see https://github.com/golang/net/blob/62affa334b73/idna/idna10.0.0.go#L387).

So I mistakenly thought this error should suffice:
https://github.com/ooni/probe-engine/blob/9d31430034e6b2bbfc8d0b08dc3b368a65e1f35e/netx/resolver/idna_test.go#L72

:thinking: 
Thanks.

**Comment by bassosimone** [comment]
> So I mistakenly thought this error should suffice:

Let me take a more in depth look at it.

**Comment by bassosimone** [comment]
Closing in favour of https://github.com/ooni/probe-engine/pull/952

**Pull request closed without merging**
