### PR TITLE
collector: unconditionally write the ReportID

### PR DESCRIPTION
**Pull request by bassosimone**
Issue reported by @FedericoCeratto

### CODE REVIEW

**Comment by FedericoCeratto** [comment]
Any functional test that can be added?

**Comment by bassosimone** [comment]
@FedericoCeratto:

> Any functional test that can be added?

Sure, I can and should do this (see https://github.com/ooni/probe-engine/issues/25). If you don't mind, I'd rather merge this critical fix and cut a release of probe-cli as well, so we have this fix in the desktop app, and then focus on adding more tests.

**Comment by hellais** [comment]
In which cases was the reportID missing from the files? Was that the bug?

I think it's OK to merge this without some checks, but we should at least document in this PR what the problem was (and how to reproduce it) so that we know how to implement a test for it in the future.

**Comment by bassosimone** [comment]
> In which cases was the reportID missing from the files? Was that the bug?

When we run MK tests, the code overwrites the full report. This is convenient because it simplifies life but then it also removes the reportID we had already set in Go code.

Another case where it may break: we have a measurement from a previous run where the upload failed and we're now resubmitting with a different measurement ID.

In both cases, the collector will accept the measurements with empty/wrong measurement ID, and then we'll have a measurement with empty/wrong measurement ID saved on disk.

I believe this fix is fine, because of the second case. The first case may call for changing the way in which MK code integrates with Go code. We may also consider that.

I'd actually start from writing functional tests, as @FedericoCeratto says, and that was actually already part of my immediate post-OTF2019 TODO list.

**Comment by hellais** [comment]
Ok understood, thanks for explaining it.

(I assume in the second case where you say "measurement ID" you mean "report ID" as well)

**Comment by bassosimone** [comment]
> (I assume in the second case where you say "measurement ID" you mean "report ID" as well)

Yes, my bad, I'm a bit 💤 today!

**Comment by bassosimone** [comment]
I'm going to proceed with merging and then I'll follow up with @FedericoCeratto for more tests

**Pull request merged**
