### PR TITLE
extended run for urlgetter

### PR DESCRIPTION
**Pull request by kelmenhorst**

### CODE REVIEW

**Review by bassosimone — APPROVED** [review]
🐳 🥳 🦜

**Comment by bassosimone** [comment]
Tests passing locally. It seems RiseupVPN is temporarily down (cc: @cyBerta).

**Comment by cyBerta** [comment]
Yes, two gateways have been down yesterday because of maintenance work.

**Comment by bassosimone** [comment]
@cyBerta thanks!

**Pull request merged**
